moma_example/moma_example/urls.py
#==========================================================================
# Copyright 2012 Lucidel, Inc., 2013 Cloudoscope Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this work except in compliance with the License.
# You may obtain a copy of the License in the LICENSE file, or at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==========================================================================

import data
from django.conf.urls import patterns, include, url
from django.contrib import admin
from moma_example import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'moma_example.views.home', name='home'),

    url(r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # User auth urls
    url(r'^accounts/login/$', 'moma_example.views.login', name='login'),
    url(r'^accounts/auth/$', 'moma_example.views.auth_view'),
    url(r'^accounts/logout/$', 'moma_example.views.logout', name='logout'),
    url(r'^accounts/loggedin/$', 'moma_example.views.loggedin'),
    url(r'^accounts/invalid/$', 'moma_example.views.invalid_login'),
    url(r'^accounts/register/$', 'moma_example.views.register_user', name='register'),
    url(r'^accounts/register_success/$', 'moma_example.views.register_success'),

    url(r'^about/$', 'data.views.about', name='about'),

    url(r'^q/home/$', 'data.views.questions_home', name='questions_home'),
    url(r'^q/edit/$', 'data.views.questions_edit'),
    url(r'^q/vote/$', 'data.views.vote'),
    url(r'^q/un_vote/$', 'data.views.un_vote'),
    url(r'^q/media/$', 'data.views.list_question_media', name='list_question_media'),
    url(r'^q/review/$', 'data.views.review_question_media', name='review_question_media'),
    url(r'^q/search/$', 'data.views.questions_search', name='questions_search'),
)

moma_example/data/forms.py
#==========================================================================
# Copyright 2012 Lucidel, Inc., 2013 Cloudoscope Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this work except in compliance with the License.
# You may obtain a copy of the License in the LICENSE file, or at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==========================================================================
from django import forms
from django.forms import HiddenInput


class QuetionEditForm(forms.Form):
    question_txt = forms.CharField(required=True, label="question_txt", widget=forms.Textarea())
    question_id = forms.CharField(required=False, label="question id",
                                 widget = forms.TextInput(attrs={'type': 'hidden',}))

    def __init__(self, *args, **kwargs):
        from django.forms.widgets import HiddenInput
        hide_condition = kwargs.pop('hide_condition',None)
        super(forms.Form, self).__init__(*args, **kwargs)
        if hide_condition:
            self.fields['question_id'].widget = HiddenInput()


class DocumentForm(forms.Form):
    docfile = forms.FileField(required=True,
        label='Upload an Image',
        help_text='Note: on a device with a camera, pressing "Choose File" would allow taking a picture. Other devices would enable image selection (not too large please...)',
        widget=forms.FileInput(attrs={'capture':"camera", 'accept':"image/*"}),
    )
    question_id = forms.CharField(required=True, label="question id",
                                  widget = forms.TextInput(
                                      attrs={'type': 'hidden',}
                                  ))

    def __init__(self, *args, **kwargs):
        from django.forms.widgets import HiddenInput
        hide_condition = kwargs.pop('hide_condition',None)
        super(forms.Form, self).__init__(*args, **kwargs)
        if hide_condition:
            self.fields['question_id'].widget = HiddenInput()

moma_example/templates/question/home.html
{% extends 'base.html' %}

{% block title %}Questions{% endblock %}


{% block content %}
    <div class="container">
        {% if message %}
            <div class="col-lg-4">
                {% if msg_err %}
                <div class="alert alert-dismissable alert-danger">
                {% else %}
                <div class="alert alert-dismissable alert-success">
                {% endif %}
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            </div>

        {% endif %}
        <h2>Questions</h2>
        <br>
        <h4>Please vote (or start a new question)</h4>
        {% for question in questions %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">By:{{ question.user.username }}
                    </h3>
                </div>
                <div class="panel-body">
                    {{ question.question }}
                    <ul class="nav nav-pills">
                        {% if question.vote_ids|length > 0 %}
                            <a class="btn btn-lg" >Votes <span class="badge">{{ question.vote_ids|length }}  </span></a>
                        {% endif %}
                        {% if the_user.id in question.vote_ids %}
                            <a class="btn btn-warning" href="/q/un_vote/?q={{ question.id }}">Un-Vote <span class="badge">-1</span></a>
                        {% else %}
                            {% if the_user.id == question.user.id %}
                                <a class="btn btn-danger" href="/q/edit/?q={{ question.id }}">Edit</a>
                            {% else %}
                                <a class="btn btn-success" href="/q/vote/?q={{ question.id }}">Vote <span class="badge">+1</span></a>
                            {% endif %}
                        {% endif %}
                        {% if question.docs.keys|length > 0 %}
                            <a class="btn btn-info" href="/q/review/?q={{ question.id }}">Media <span class="badge">{{ question.docs.keys|length }}</span></a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        {% endfor %}
        <br>
        <a href="/q/edit/" class="btn btn-primary">I have a new question</a>
        <a href="/q/home/" class="btn btn-default">Refresh</a>
    </div>
{% endblock %}

moma_example/templates/question/question_form.html
{% extends 'base.html' %}
{% load bootstrap  %}

{% block title %}Edit Question{% endblock %}


{% block content %}
    <div class="container">

        <br>
        <div class="offset2 span3">
            <h1>Edit Question</h1>
            <form action="/q/edit/" method="post">{% csrf_token %}
                {{ form }}
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <a href="/q/home/" class="btn btn-default">Cancel</a>
                        <input type="submit" class="btn btn-success" value="Submit / add media">
                    </div>
                </div>

            </form>
        </div>

    </div>

{% endblock %}

moma_example/templates/question/question_media.html
{% extends 'base.html' %}
{% load bootstrap  %}

{% block title %}Question Media{% endblock %}

{% block css %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <style>
        #yourimage {
            width:100%;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="container">

        <br>
        <div class="offset2 span3">
            {% if question.user != the_user %}
                <h1>Review Question Media</h1>
            {% else %}
                <h1>Edit Question Media</h1>
            {% endif %}
            <!-- List of uploaded documents -->
            {% if documents %}
                <ul>
                    {% for document in documents %}
                        <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a> <img src="{{ document.docfile.thumb }}"></li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No documents.</p>
            {% endif %}

            {% if question %}
                {% if question.user != the_user %}
                    <div class="col-lg-4">
                        <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ the_user }}, you can review the media for this question (this question was submitted by: {{ question.user }}).
                        </div>
                    </div>

                    {% else %}
                    <!-- Upload form. Note enctype attribute! -->
                    <form action="{% url list_question_media %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                        {% csrf_token %}
                        <div class="form-group">
                            <p>{{ form.non_field_errors }}</p>
                            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
                            <p>
                                {{ form.docfile.errors }}
                                {{ form.docfile }}
                                <div hidden>{{ form.question_id }}</div>

                            </p>
                            <p><input type="submit" value="Upload" /></p>
                            <a href="/q/home/" class="btn btn-default">Done changes</a>
                            <a href="/q/edit/?q={{ question.id }}" class="btn btn-default">Back to edit question</a>
                        </div>
                    </form>
                    <img id="yourimage">
                {% endif %}
            {% endif %}
        </div>

    </div>

    <script>
        var desiredWidth;

        $(document).ready(function() {
            console.log('onReady');
            $("#id_docfile").on("change",gotPic);
            desiredWidth = window.innerWidth;

            if(!("url" in window) && ("webkitURL" in window)) {
                window.URL = window.webkitURL;
            }

        });


        //Credit: https://www.youtube.com/watch?v=EPYnGFEcis4&feature=youtube_gdata_player
        function gotPic(event) {
            if(event.target.files.length == 1 &&
                     event.target.files[0].type.indexOf("image/") == 0) {
                $("#yourimage").attr("src",URL.createObjectURL(event.target.files[0]));
            }
        }



    </script>

{% endblock %}

moma_example/templates/question/review_question_media.html
{% extends 'base.html' %}

{% block title %}Review Question Media{% endblock %}


{% block content %}
    <div class="container">
        <h2>Review Question Media</h2>
        <br>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">By:{{ question.user.username }}
                </h3>
            </div>
            <div class="panel-body">
                {{ question.question }}
                <ul class="nav nav-pills">
                    {% if question.vote_ids|length > 0 %}
                        <a class="btn btn-lg" >Votes <span class="badge">{{ question.vote_ids|length }}  </span></a>
                    {% endif %}
                    {% if the_user.id in question.vote_ids %}
                        <a class="btn btn-warning" href="/q/un_vote/?q={{ question.id }}">Un-Vote <span class="badge">-1</span></a>
                    {% else %}
                        {% if the_user.id == question.user.id %}
                            <a class="btn btn-danger" href="/q/edit/?q={{ question.id }}">Edit</a>
                        {% else %}
                            <a class="btn btn-success" href="/q/vote/?q={{ question.id }}">Vote <span class="badge">+1</span></a>
                        {% endif %}
                    {% endif %}
                    {% if question.docs.keys|length > 0 or question.user == the_user %}
                        <a class="btn btn-info" href="/q/media/?q={{ question.id }}">Media <span class="badge">{{ question.docs.keys|length }}</span></a>
                    {% endif %}
                </ul>
            </div>
        </div>
        <h3>Review Question Media</h3>
        {% for doc_name, doc_url in documents.iteritems %}
            {{ doc_name }}
            <img src="{{ doc_url }}" alt="{{ doc_name }}">
        {% endfor %}
        <br>
        <a href="/q/home/" class="btn btn-default">Back</a>
    </div>
{% endblock %}